src/app/playlist/__init__.py
from flask import Blueprint

bp = Blueprint("playlist", __name__)

from app.playlist import routes

src/app/playlist/routes.py
from datetime import datetime
from flask import (
    flash,
    g,
    Markup,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from random import shuffle

from app.authentication import guest_auth
from app.models import Song
from app.playlist import bp

from ..forms import CreatePlaylistForm
from ..spotify import spotify


@bp.route("/", methods=["GET"])
def show_playlists_page():
    """
    Shows a list of all playlists on user Spotify account
    """

    user_id = g.user.spotify_id
    playlists = spotify.get_user_playlists(user_id)

    playlists_data = playlists[0] if playlists else None
    profile_url = playlists[1] if playlists else None

    return render_template(
        "playlist/playlists.html",
        playlists_data=playlists_data,
        profile_url=profile_url,
    )


@bp.route("/delete", methods=["POST"])
def delete_playlist():
    """
    Delete the selected playlist from Spotify
    """
    playlist_id = request.form.get("playlist_to_delete")
    spotify.unfollow_playlist(playlist_id)
    flash("Deleted playlist", "danger")
    return redirect(url_for("playlist.show_playlists_page"))


@bp.route("/create", methods=["POST"])
def create_custom_playlist():
    form = CreatePlaylistForm()

    if form.validate_on_submit():
        vibe = round(form.vibe.data, 2)
        title = form.title.data

        if not title:
            title = f"my-playlist-{datetime.now().date()}"

        session["title"] = title

        if g.user:
            spotify.create_user_playlist(vibe)
        else:
            guest_auth.authorize()
            spotify.create_user_playlist(vibe)

        return render_template("playlist/new-playlist.html", title=title)


@bp.route("/<title>", methods=["GET"])
def show_preset_playlist(title):
    """
    Creates a playlist with the chosen vibe for user.
    Playlists are generated using existing songs in the database if user is a guest.
    """

    if title == "preset-sad":
        vibe = 0.10
    elif title == "preset-neutral":
        vibe = 0.50
    else:
        vibe = 1.00

    session["title"] = title

    if g.user:
        spotify.create_user_playlist(vibe)
        return render_template("playlist/new-playlist.html")
    else:
        songs = Song.query.filter(Song.valence.between(vibe - 0.15, vibe + 0.15)).all()
        shuffle(songs)
        return render_template("playlist/preset-playlist-guest.html", songs=songs[:15])


@bp.route("/<title>/add-playlist", methods=["POST"])
def add_playlist_to_spotify(title):
    if g.user:
        user_id = g.user.spotify_id
        playlist_info = spotify.create_empty_spotify_playlist(user_id)
        playlist_id = playlist_info["id"]
        playlist_url = playlist_info["external_urls"]["spotify"]

        uris = [track["uri"] for track in session["playlist"]]

        spotify.populate_playlist(playlist_id, uris)

        flash(
            Markup(
                f"<a href='{playlist_url}' target='_blank' class='text-deepPurple underline'>Successfully added playlist to Spotify</a>"
            ),
            "success",
        )

        return redirect("/playlist")

src/app/templates/playlist/guest-preset-playlist.html
{% extends 'base.html' %}

{% block title %}Playlists{% endblock %}

{% block content %}
<!-- Guest Preset Playlist Page -->

  <div
    id="playlist"
    class="h-full bg-darkBlue"
    data-token="{{session['access_token']}}"
  >
    <div class="h-full overflow-y-auto">
      <h2
        class="text-6xl text-center text-lightGreen text-decoration-line: underline font-heading py-3"
      >
        {{session["title"]}}
      </h2>
      <!-- Flex container -->
      <div class="flex flex-row justify-evenly h-4/5">
        <!-- Flex container -->
        <div class="flex flex-col w-2/5">
          <!-- List of tracks -->
          <div
            class="flex flex-col items-center overflow-y-auto border-solid border-white border-2 rounded-md"
          >
            {% for track in songs%}
              <div
                class="track w-full text-center bg-slate-700 cursor-pointer hover:bg-lightGreen"
              >
                <p
                  class="w-full h-full p-3"
                  data-id="{{track.id}}"
                  data-image="{{track.album_image_url}}"
                >
                  {{track.name}} - {{track.artist}}
                </p>
              </div>
            {% endfor %}
          </div>

          <button
            id="add-playlist-btn"
            class="border-2 border-white bg-deepPurple rounded-md p-3 w-full hover:bg-black hover:border-lightGreen hover:text-lightGreen transition duration-1500"
            disabled
          >
            Sign In to Save to Spotify
          </button>
        </div>
        <!-- Song Information / Player-->
        <div class="w-2/5 flex flex-col justify-between items-center">
          <img
            class="h-4/5 border-solid border-white border-2 rounded-md"
            id="album-image"
            src="{{songs[0]['album_image_url']}}"
            alt=""
          />
          <iframe
            class="iframe-track border-solid border-white border-2 rounded-md"
            src="https://open.spotify.com/embed/track/{{songs[0]['id']}}"
            frameborder="0"
            width="100%"
            height="80"
            allowtransparency="true"
            allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
          ></iframe>
        </div>
      </div>
      <!-- Footer -->
      <footer class="absolute bottom-0 w-full flex justify-end bg-black text-2xl">
        <div class="p-3 space-x-2">
          <a
            href="https://www.linkedin.com/in/tsuyoshi-koyama-2018/"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-linkedin fa-xl"></i
          ></a>
          <a
            href="https://github.com/tsuyokoya/vibify"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-github fa-xl"></i
          ></a>
        </div>
      </footer>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script src="../static/js/playlist.js"></script>
{% endblock %}

src/app/templates/playlist/new-playlist.html
{% extends 'base.html' %}

{% block title %}Playlists{% endblock %}

{% block content %}
<!-- Playlist Page -->

  <div
    id="playlist"
    class="h-full bg-darkBlue"
    data-token="{{session['access_token']}}"
  >
    <div class="h-full overflow-y-auto">
      <h2
        class="text-6xl text-center text-lightGreen text-decoration-line: underline font-heading py-3"
      >
        {{session["title"]}}
      </h2>
      <!-- Flex container -->
      <div class="flex flex-row justify-evenly h-4/5">
        <!-- Flex container -->
        <div class="flex flex-col w-2/5">
          <!-- List of tracks -->
          <div
            class="flex flex-col items-center overflow-y-auto border-solid border-white border-2 rounded-md"
          >
            {% for track in session["playlist"]%}
              <div
                class="track w-full text-center bg-slate-700 cursor-pointer hover:bg-lightGreen"
              >
                <p
                  class="w-full h-full p-3"
                  data-id="{{track.id}}"
                  data-image="{{track.album_image_url}}"
                >
                  {{track.name}} - {{track.artist}}
                </p>
              </div>
            {% endfor %}
          </div>
          {% if session["curr_user"] %}
            <form
              id="add-playlist-form"
              action="{{url_for('playlist.add_playlist_to_spotify', title=title)}}"
              method="post"
            >
              <button
                id="add-playlist-btn"
                class="border-2 border-white bg-deepPurple rounded-md p-3 w-full hover:bg-black hover:border-lightGreen hover:text-lightGreen transition duration-1500"
              >
                Add to Spotify
              </button>
            </form>
          {% else %}

            <button
              id="add-playlist-btn"
              class="border-2 border-white bg-deepPurple rounded-md p-3 w-full hover:bg-black hover:border-lightGreen hover:text-lightGreen transition duration-1500"
              disabled
            >
              Sign In to Save to Spotify
            </button>

          {% endif %}
        </div>
        <!-- Song Information / Player-->
        <div class="w-2/5 flex flex-col justify-between items-center">
          <img
            class="h-4/5 border-solid border-white border-2 rounded-md"
            id="album-image"
            src="{{session['playlist'][0]['album_image_url']}}"
            alt=""
          />
          <iframe
            class="iframe-track border-solid border-white border-2 rounded-md"
            src="https://open.spotify.com/embed/track/{{session['playlist'][0]['id']}}"
            frameborder="0"
            width="100%"
            height="80"
            allowtransparency="true"
            allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
          ></iframe>
        </div>
      </div>
      <!-- Footer -->
      <footer class="absolute bottom-0 w-full flex justify-end bg-black text-2xl">
        <div class="p-3 space-x-2">
          <a
            href="https://www.linkedin.com/in/tsuyoshi-koyama-2018/"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-linkedin fa-xl"></i
          ></a>
          <a
            href="https://github.com/tsuyokoya/vibify"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-github fa-xl"></i
          ></a>
        </div>
      </footer>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script src="../static/js/playlist.js"></script>
{% endblock %}

src/app/templates/playlist/playlist.html
{% extends 'base.html' %}

{% block title %}Playlists{% endblock %}

{% block content %}
<!-- Playlist Page -->

  <div
    id="playlist"
    class="h-full bg-darkBlue"
    data-token="{{session['access_token']}}"
  >
    <div class="h-full overflow-y-auto">
      <h2
        class="text-6xl text-center text-lightGreen text-decoration-line: underline font-heading py-3"
      >
        {{session["title"]}}
      </h2>
      <!-- Flex container -->
      <div class="flex flex-row justify-evenly h-4/5">
        <!-- Flex container -->
        <div class="flex flex-col w-2/5">
          <!-- List of tracks -->
          <div
            class="flex flex-col items-center overflow-y-auto border-solid border-white border-2 rounded-md"
          >
            {% for track in session["playlist"]%}
              <div
                class="track w-full text-center bg-slate-700 cursor-pointer hover:bg-lightGreen"
              >
                <p
                  class="w-full h-full p-3"
                  data-id="{{track.id}}"
                  data-image="{{track.album_image_url}}"
                >
                  {{track.name}} - {{track.artist}}
                </p>
              </div>
            {% endfor %}
          </div>
          {% if session["curr_user"] %}
            <form
              id="add-playlist-form"
              action="/playlist/{{session['title']}}"
              method="post"
            >
              <button
                id="add-playlist-btn"
                class="border-2 border-white bg-deepPurple rounded-md p-3 w-full hover:bg-black hover:border-lightGreen hover:text-lightGreen transition duration-1500"
              >
                Add to Spotify
              </button>
            </form>
          {% else %}

            <button
              id="add-playlist-btn"
              class="border-2 border-white bg-deepPurple rounded-md p-3 w-full hover:bg-black hover:border-lightGreen hover:text-lightGreen transition duration-1500"
              disabled
            >
              Sign In to Save to Spotify
            </button>

          {% endif %}
        </div>
        <!-- Song Information / Player-->
        <div class="w-2/5 flex flex-col justify-between items-center">
          <img
            class="h-4/5 border-solid border-white border-2 rounded-md"
            id="album-image"
            src="{{session['playlist'][0]['album_image_url']}}"
            alt=""
          />
          <iframe
            class="iframe-track border-solid border-white border-2 rounded-md"
            src="https://open.spotify.com/embed/track/{{session['playlist'][0]['id']}}"
            frameborder="0"
            width="100%"
            height="80"
            allowtransparency="true"
            allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
          ></iframe>
        </div>
      </div>
      <!-- Footer -->
      <footer class="absolute bottom-0 w-full flex justify-end bg-black text-2xl">
        <div class="p-3 space-x-2">
          <a
            href="https://www.linkedin.com/in/tsuyoshi-koyama-2018/"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-linkedin fa-xl"></i
          ></a>
          <a
            href="https://github.com/tsuyokoya/vibify"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-github fa-xl"></i
          ></a>
        </div>
      </footer>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script src="../static/js/playlist.js"></script>
{% endblock %}

src/app/templates/playlist/playlists.html
{% extends 'base.html' %}

{% block title %}Playlists{% endblock %}

{% block content %}
  <!-- User Playlists Page -->

  <!-- Flex container -->
  <div class="relative h-full flex flex-col items-center">
    <h2
      class="text-6xl text-center text-lightGreen text-decoration-line: underline font-heading py-3 mb-2"
    >
      {{g.user["name"]}}'s Playlists
    </h2>
    <!-- Spotify Profile link -->
    {% if profile_url %}
      <div
        class="flex flex-col w-1/5 m-2 border-2 border-white bg-deepPurple rounded-md hover:scale-110 hover:bg-white hover:border-lightGreen hover:text-lightGreen transition duration-1500"
      >
        <a href="{{profile_url}}" target="_blank" class="p-3">
          <h3 class="text-center text-xl">My Spotify Profile</h3>
        </a>
      </div>
    {% endif %}
    <!-- List of Spotify playlists -->
    <div class="flex flex-wrap justify-evenly">

      {% if playlists_data %}
        {% for playlist in playlists_data %}
          <div
            class="flex flex-col w-96 m-7 border-2 border-white rounded-md hover:scale-110 hover:border-lightGreen hover:bg-black hover:text-lightGreen transition duration-1500"
          >
            <a href="{{playlist.url}}" target="_blank" class="p-3">
              <h3 class="text-center text-3xl mb-2">{{playlist.name}}</h3>
              <img
                src="{{playlist.image}}"
                class="h-80 w-full"
                alt="playlist image"
              />
            </a>

            <form
              action="{{url_for('playlist.delete_playlist')}}"
              method="POST"
              class="cursor-pointer text-center bg-deepPurple rounded-md w-full hover:bg-white hover:border-lightGreen hover:text-lightGreen transition duration-1500"
            >
              <input
                type="hidden"
                value="{{ playlist.id }}"
                name="playlist_to_delete"
              />
              <button class="w-full h-full p-3">Delete</button>
            </form>
          </div>
        {% endfor %}
      {% else %}
        <h2>Looks like your Spotify account doesn't have any playlists!</h2>
      {% endif %}

    </div>
  </div>

{% endblock %}

src/app/templates/playlist/preset-playlist-guest.html
{% extends 'base.html' %}

{% block title %}Playlists{% endblock %}

{% block content %}
<!-- Guest Preset Playlist Page -->

  <div
    id="playlist"
    class="h-full bg-darkBlue"
    data-token="{{session['access_token']}}"
  >
    <div class="h-full overflow-y-auto">
      <h2
        class="text-6xl text-center text-lightGreen text-decoration-line: underline font-heading py-3"
      >
        {{session["title"]}}
      </h2>
      <!-- Flex container -->
      <div class="flex flex-row justify-evenly h-4/5">
        <!-- Flex container -->
        <div class="flex flex-col w-2/5">
          <!-- List of tracks -->
          <div
            class="flex flex-col items-center overflow-y-auto border-solid border-white border-2 rounded-md"
          >
            {% for track in songs%}
              <div
                class="track w-full text-center bg-slate-700 cursor-pointer hover:bg-lightGreen"
              >
                <p
                  class="w-full h-full p-3"
                  data-id="{{track.id}}"
                  data-image="{{track.album_image_url}}"
                >
                  {{track.name}} - {{track.artist}}
                </p>
              </div>
            {% endfor %}
          </div>

          <button
            id="add-playlist-btn"
            class="border-2 border-white bg-deepPurple rounded-md p-3 w-full hover:bg-black hover:border-lightGreen hover:text-lightGreen transition duration-1500"
            disabled
          >
            Sign In to Save to Spotify
          </button>
        </div>
        <!-- Song Information / Player-->
        <div class="w-2/5 flex flex-col justify-between items-center">
          <img
            class="h-4/5 border-solid border-white border-2 rounded-md"
            id="album-image"
            src="{{songs[0]['album_image_url']}}"
            alt=""
          />
          <iframe
            class="iframe-track border-solid border-white border-2 rounded-md"
            src="https://open.spotify.com/embed/track/{{songs[0]['id']}}"
            frameborder="0"
            width="100%"
            height="80"
            allowtransparency="true"
            allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
          ></iframe>
        </div>
      </div>
      <!-- Footer -->
      <footer class="absolute bottom-0 w-full flex justify-end bg-black text-2xl">
        <div class="p-3 space-x-2">
          <a
            href="https://www.linkedin.com/in/tsuyoshi-koyama-2018/"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-linkedin fa-xl"></i
          ></a>
          <a
            href="https://github.com/tsuyokoya/vibify"
            class="hover:text-darkBlue"
            target="blank"
            ><i class="fa-brands fa-github fa-xl"></i
          ></a>
        </div>
      </footer>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script src="../static/js/playlist.js"></script>
{% endblock %}